### ISSUE TITLE
Hello. This project is abandoned, isn't? (It seems ADK pretty too...)

### ISSUE THREAD

**Issue by q2dg** [follower/android-arduino-handbag#1]
I only wanted to confirm. Thanks

**Comment by follower** [comment]
Rather than abandoned, I'd prefer to say it's having a very long sleep. :)

The ADK, however, does seem to have been abandoned long ago…

Was there a particular reason for your enquiry?

**Comment by q2dg** [comment]
Well, I'm writing a book about Arduino and Android (in spanish) and I want to be sure that techniques I explain were currently used. Thanks!

**Comment by follower** [comment]
👍
